
package com.creativitystack.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadoraServiceImpService", targetNamespace = "http://service.webservice.creativitystack.com/", wsdlLocation = "http://localhost:8080/ws-project-1.0/CalculadoraServiceImp?wsdl")
public class CalculadoraServiceImpService
    extends Service
{

    private final static URL CALCULADORASERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORASERVICEIMPSERVICE_EXCEPTION;
    private final static QName CALCULADORASERVICEIMPSERVICE_QNAME = new QName("http://service.webservice.creativitystack.com/", "CalculadoraServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws-project-1.0/CalculadoraServiceImp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORASERVICEIMPSERVICE_WSDL_LOCATION = url;
        CALCULADORASERVICEIMPSERVICE_EXCEPTION = e;
    }

    public CalculadoraServiceImpService() {
        super(__getWsdlLocation(), CALCULADORASERVICEIMPSERVICE_QNAME);
    }

    public CalculadoraServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORASERVICEIMPSERVICE_QNAME, features);
    }

    public CalculadoraServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORASERVICEIMPSERVICE_QNAME);
    }

    public CalculadoraServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORASERVICEIMPSERVICE_QNAME, features);
    }

    public CalculadoraServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculadoraService
     */
    @WebEndpoint(name = "calculadoraPort")
    public CalculadoraService getCalculadoraPort() {
        return super.getPort(new QName("http://service.webservice.creativitystack.com/", "calculadoraPort"), CalculadoraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraService
     */
    @WebEndpoint(name = "calculadoraPort")
    public CalculadoraService getCalculadoraPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.creativitystack.com/", "calculadoraPort"), CalculadoraService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORASERVICEIMPSERVICE_EXCEPTION!= null) {
            throw CALCULADORASERVICEIMPSERVICE_EXCEPTION;
        }
        return CALCULADORASERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
