
package com.creativitystack.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ws_project.calculator.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraService", targetNamespace = "http://ws-project/calculator")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://ws-project/calculator", className = "ws_project.calculator.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://ws-project/calculator", className = "ws_project.calculator.AdditionResponse")
    public int addition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws-project/calculator", className = "ws_project.calculator.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws-project/calculator", className = "ws_project.calculator.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
